"""generator.py — Generate Java files from CellML.

Generates:
  1. AbstractCellmlModel.java — shared base with abstract applyBoundaryConditions(double t)
  2. <ModelName>.java — concrete model with named fields (abstract: user must subclass)
  3. <ModelName>FruitService.java — optional FruitServiceAPI wrapper (--with-fruit-service)
"""
import ast
import os
import math

from libcellml import Parser, Analyser, Generator, GeneratorProfile

from .metadata import extract_model_metadata, get_cellml_model_name, to_java_class_name, package_to_path
from .emitter import JavaEmitter


def generate_abstract_base(package, output_dir):
    """Write AbstractCellmlModel.java — shared base class with abstract applyBoundaryConditions."""
    pkg_path = os.path.join(output_dir, package_to_path(package))
    os.makedirs(pkg_path, exist_ok=True)
    filepath = os.path.join(pkg_path, "AbstractCellmlModel.java")

    code = _get_abstract_base_template(package)
    with open(filepath, "w") as f:
        f.write(code)
    return filepath


def _get_abstract_base_template(package):
    return f"""/*
 * AbstractCellmlModel.java — Shared abstract base for all CellML-generated models.
 *
 * Generated by cellml2fruitcropxl. This is a static template (not model-specific).
 * Provides the FirstOrderDifferentialEquations interface and the state/field
 * bridge pattern. The key feature is the ABSTRACT applyBoundaryConditions(double t)
 * method — the user MUST implement this in a subclass to set external forcing
 * inputs (e.g. pasfls, u_stem_water, VPD) before the model equations are evaluated.
 */
package {package};

import org.apache.commons.math3.ode.FirstOrderDifferentialEquations;

/**
 * Abstract base for CellML-generated ODE models.
 * <p>
 * The computeDerivatives template method calls:
 * <ol>
 *   <li>loadStates(y) — copy integrator state to named fields</li>
 *   <li>applyBoundaryConditions(t) — ABSTRACT: user sets external inputs</li>
 *   <li>computeComputedConstants() — re-derive constants with user's inputs</li>
 *   <li>computeRates(t) — compute ODE right-hand side</li>
 *   <li>storeRates(yDot) — copy named rates to integrator output</li>
 * </ol>
 */
public abstract class AbstractCellmlModel implements FirstOrderDifferentialEquations {{

    protected final String[] stateNames;
    protected final double[] initialValues;
    protected final double[] states;

    protected AbstractCellmlModel(String[] stateNames, double[] initialValues) {{
        this.stateNames = stateNames;
        this.initialValues = initialValues;
        this.states = new double[stateNames.length];
        System.arraycopy(initialValues, 0, states, 0, stateNames.length);
    }}

    @Override
    public int getDimension() {{ return states.length; }}

    /**
     * Template method — called by the ODE integrator at each evaluation.
     * The ordering is critical: applyBoundaryConditions is called BEFORE
     * computeComputedConstants so that derived constants reflect updated forcing.
     */
    @Override
    public void computeDerivatives(double voi, double[] y, double[] yDot) {{
        System.arraycopy(y, 0, states, 0, states.length);
        loadStates(y);
        applyBoundaryConditions(voi);
        computeComputedConstants();
        computeRates(voi);
        storeRates(yDot);
    }}

    // === Abstract methods — the generated concrete model implements: ===

    /** Copy integrator state vector y[] into named state fields. */
    protected abstract void loadStates(double[] y);

    /** Copy named derivative fields (d_*_dt) into the integrator's yDot[]. */
    protected abstract void storeRates(double[] yDot);

    /** Compute derived constants (re-call when external forcing changes). */
    public abstract void computeComputedConstants();

    /** Compute ODE rates at time voi. */
    public abstract void computeRates(double voi);

    // === USER MUST IMPLEMENT THIS in a subclass: ===

    /**
     * Apply boundary conditions at time voi.
     * <p>
     * <b>ABSTRACT — the user MUST implement this in a subclass.</b> This is where
     * you set external forcing inputs (e.g. pasfls, u_stem_water, VPD, phloem
     * concentrations) before the model equations are evaluated.
     * <p>
     * This method is called BEFORE computeComputedConstants() so that derived
     * constants (which depend on the forcing inputs) are correctly recomputed.
     * <p>
     * Example implementation:
     * <pre>
     * &#64;Override
     * protected void applyBoundaryConditions(double t) {{
     *     pasfls = interpolatePasfls(t);  // from CSV
     *     u_stem_water = interpolatePsiStem(t);  // from climate data
     * }}
     * </pre>
     *
     * @param voi current time (in the model's time unit, typically days)
     */
    protected abstract void applyBoundaryConditions(double voi);

    // === Common accessors ===

    public double[] getStates() {{ return states.clone(); }}

    public void setStates(double[] s) {{
        System.arraycopy(s, 0, states, 0, states.length);
        loadStates(states);
    }}

    public double getState(String name) {{
        for (int i = 0; i < stateNames.length; i++)
            if (stateNames[i].equals(name)) return states[i];
        throw new IllegalArgumentException("Unknown state: " + name);
    }}

    public void setState(String name, double value) {{
        for (int i = 0; i < stateNames.length; i++) {{
            if (stateNames[i].equals(name)) {{
                states[i] = value;
                loadStates(states);
                return;
            }}
        }}
        throw new IllegalArgumentException("Unknown state: " + name);
    }}

    public String[] getStateNames() {{ return stateNames; }}
    public int getStateCount() {{ return states.length; }}
}}
"""


def _safe_float(val):
    """Convert a libcellml initial_value (possibly string/None/NaN) to float."""
    if val is None:
        return 0.0
    try:
        f = float(val)
        return 0.0 if f != f else f  # NaN check
    except (ValueError, TypeError):
        return 0.0


def generate_model(cellml_path, model_name, class_name, package, output_dir):
    """Generate the concrete model class with named fields (abstract: user must subclass)."""
    with open(cellml_path) as f:
        cellml_content = f.read()

    state_info, var_info = extract_model_metadata(cellml_content)

    # Generate raw Python from libcellml.
    parser = Parser()
    parser.setStrict(False)
    model = parser.parseModel(cellml_content)
    analyser = Analyser()
    analyser.analyseModel(model)
    generator = Generator()
    profile = GeneratorProfile(GeneratorProfile.Profile.PYTHON)
    raw_python = generator.implementationCode(analyser.analyserModel(), profile)

    # Parse Python AST and translate to Java with named fields.
    tree = ast.parse(raw_python)
    emitter = JavaEmitter(state_info, var_info)

    # Classify variables.
    constants = [(i, v) for i, v in enumerate(var_info) if v["type"] == "Constant"]
    computed_constants = [(i, v) for i, v in enumerate(var_info) if v["type"] == "ComputedConstant"]
    algebraics = [(i, v) for i, v in enumerate(var_info) if v["type"] == "Algebraic"]

    # Translate function bodies.
    func_bodies = {}
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name in (
                "compute_rates", "compute_variables", "compute_computed_constants"):
            stmts = [emitter.emit_stmt(s) for s in node.body]
            func_bodies[node.name] = "\n".join(stmts)

    # Assemble Java class.
    state_names_list = [s["name"] for s in state_info]
    init_values_list = [_safe_float(s["initial_value"]) for s in state_info]

    lines = []
    lines.append(f"/*")
    lines.append(f" * {class_name}.java — AUTO-GENERATED from {os.path.basename(cellml_path)} by cellml2fruitcropxl.")
    lines.append(f" * CellML model name: \"{model_name}\"")
    lines.append(f" *")
    lines.append(f" * This class is ABSTRACT — it does NOT implement applyBoundaryConditions().")
    lines.append(f" * You MUST create a subclass (e.g. {class_name}Sim) and implement")
    lines.append(f" * applyBoundaryConditions(double t) to set external forcing inputs.")
    lines.append(f" *")
    lines.append(f" * Regenerate: cellml2fruitcropxl --cellml {os.path.basename(cellml_path)} --package {package}")
    lines.append(f" */")
    lines.append(f"package {package};")
    lines.append("")
    lines.append(f"public abstract class {class_name} extends AbstractCellmlModel {{")
    lines.append("")
    lines.append(f"    public static final int STATE_COUNT = {len(state_info)};")
    lines.append(f"    public static final int VARIABLE_COUNT = {len(var_info)};")
    lines.append("")

    # State fields
    lines.append("    // === State variables — initial values from CellML ===")
    for s in state_info:
        iv = _safe_float(s["initial_value"])
        lines.append(f"    public double {s['name']} = {iv};")
    lines.append("")

    # Rate fields
    lines.append("    // === Rate derivatives ===")
    for s in state_info:
        lines.append(f"    public double d_{s['name']}_dt = 0.0;")
    lines.append("")

    # Constants
    if constants:
        lines.append("    // === Constants (from CellML initial_value) ===")
        for _, v in constants:
            iv = _safe_float(v["initial_value"])
            lines.append(f"    public double {v['name']} = {iv};")
        lines.append("")

    # Computed constants
    if computed_constants:
        lines.append("    // === Computed constants ===")
        for _, v in computed_constants:
            lines.append(f"    public double {v['name']} = 0.0;")
        lines.append("")

    # Algebraics
    if algebraics:
        lines.append("    // === Algebraic variables ===")
        for _, v in algebraics:
            lines.append(f"    public double {v['name']} = 0.0;")
        lines.append("")

    # Constructor
    names_str = ", ".join('"' + n + '"' for n in state_names_list)
    vals_str = ", ".join(repr(v) for v in init_values_list)
    lines.append(f"    public {class_name}() {{")
    lines.append(f"        super(new String[]{{{names_str}}}, new double[]{{{vals_str}}});")
    lines.append(f"        loadStates(states);")
    lines.append(f"    }}")
    lines.append("")

    # loadStates / storeRates
    lines.append("    @Override")
    lines.append("    protected void loadStates(double[] y) {")
    for i, s in enumerate(state_info):
        lines.append(f"        {s['name']} = y[{i}];")
    lines.append("    }")
    lines.append("")
    lines.append("    @Override")
    lines.append("    protected void storeRates(double[] yDot) {")
    for i, s in enumerate(state_info):
        lines.append(f"        yDot[{i}] = d_{s['name']}_dt;")
    lines.append("    }")
    lines.append("")

    # computeComputedConstants
    if "compute_computed_constants" in func_bodies:
        lines.append("    @Override")
        lines.append("    public void computeComputedConstants() {")
        lines.append(func_bodies["compute_computed_constants"])
        lines.append("    }")
        lines.append("")

    # computeRates
    if "compute_rates" in func_bodies:
        lines.append("    @Override")
        lines.append("    public void computeRates(double voi) {")
        lines.append(func_bodies["compute_rates"])
        lines.append("    }")
        lines.append("")

    # computeVariables
    if "compute_variables" in func_bodies:
        lines.append("    /** Compute all algebraic variables for output/logging. */")
        lines.append("    public void computeVariables(double voi) {")
        lines.append(func_bodies["compute_variables"])
        lines.append("    }")
        lines.append("")

    # Parameter accessors
    lines.append("    // === Parameter accessors ===")
    # Generic parameter setter for all constants
    lines.append("    public void setParameter(String name, double value) {")
    lines.append("        switch (name) {")
    for _, v in constants:
        lines.append(f"            case \"{v['name']}\": {v['name']} = value; break;")
    lines.append("            default: throw new IllegalArgumentException(\"Unknown parameter: \" + name);")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    code = "\n".join(lines)
    pkg_path = os.path.join(output_dir, package_to_path(package))
    os.makedirs(pkg_path, exist_ok=True)
    filepath = os.path.join(pkg_path, f"{class_name}.java")
    with open(filepath, "w") as f:
        f.write(code)
    return filepath


def generate_model_interface(package, output_dir):
    """Generate Model.java — minimal sub-model interface (no jfruit2 dependency)."""
    pkg_path = os.path.join(output_dir, package_to_path(package))
    os.makedirs(pkg_path, exist_ok=True)
    filepath = os.path.join(pkg_path, "Model.java")
    code = """/*
 * Model.java — Minimal sub-model interface for step-driven simulation.
 *
 * Provided by cellml2fruitcropxl so users don't need a jfruit2 dependency.
 * This resembles org.inra.psh.jfruit2.model.Model by method surface. Java uses
 * nominal interface typing, so an external jfruit2/FruitCropXL Model still
 * requires an explicit adapter in the consuming application.
 *
 * The Model interface enables:
 * - Step-driven simulation: compute() advances one step, getOutput() reads results
 * - Multi-model coupling: link(fms) exchanges data between models
 * - A small delegation surface for an explicit FruitCropXL adapter
 */
package %s;

import java.io.Serializable;
import java.util.ArrayList;

public interface Model extends Serializable {
    /** Initialise the model (set initial states, compute constants). */
    void init();

    /** @return number of output values. */
    int getOLength();

    /** @return the output vector (state values). */
    double[] getOutput();

    /** Advance the simulation by one time step. */
    void compute();

    /** Exchange data with other models in a multi-model system. */
    void link(ArrayList<Model> fms);
}
""" % package
    with open(filepath, "w") as f:
        f.write(code)
    return filepath


def generate_fruit_service_api(package, output_dir):
    """Generate FruitServiceAPI.java — extends Model, adds FruitService contract."""
    pkg_path = os.path.join(output_dir, package_to_path(package))
    os.makedirs(pkg_path, exist_ok=True)
    filepath = os.path.join(pkg_path, "FruitServiceAPI.java")
    code = """/*
 * FruitServiceAPI.java — Standardised FruitService contract for CellML models.
 *
 * Extends Model and adds the FruitService surface (step, getRawValues,
 * getJsonValues, fromArray, syncOutputs, setDelta, initOutputHeaders).
 * Provided by cellml2fruitcropxl — no jfruit2 dependency.
 */
package %s;

import java.util.Map;

public interface FruitServiceAPI extends Model {
    /** Advance one integrated time step (compute + link). */
    void step();

    /** @return raw output values (state vector). */
    double[] getRawValues();

    /** @return named output values (header -> value). */
    Map<String, Double> getJsonValues();

    /** Push driving inputs (forcing) at a given age. */
    void fromArray(int ageMin, double[] values);

    /** Read state back from named outputs. */
    void syncOutputs(Map<String, Double> outputs);

    /** Set the time step in minutes. */
    void setDelta(int delta);

    /** @return the time step in minutes. */
    int getDelta();

    /** Build the output header list. */
    void initOutputHeaders();
}
""" % package
    with open(filepath, "w") as f:
        f.write(code)
    return filepath


def generate_fruit_service(class_name, model_name, package, output_dir, state_info):
    """Generate the FruitService wrapper (concrete, takes model instance)."""
    service_name = f"{class_name}FruitService"
    header_entries = ", ".join('"' + s["name"] + '"' for s in state_info)

    code = f"""/*
 * {service_name}.java — FruitServiceAPI wrapper for {class_name}.
 * AUTO-GENERATED by cellml2fruitcropxl from CellML model "{model_name}".
 *
 * This wrapper implements Model + FruitServiceAPI (provided by this package,
 * NOT from jfruit2). It owns the integrator and provides step-driven simulation.
 *
 * Usage:
 *   {class_name} model = new MySim();  // user's concrete subclass
 *   {service_name} svc = new {service_name}(model, 60);  // delta=60 min
 *   svc.init();
 *   svc.fromArray(ageMin, new double[]{{pasfls}});
 *   svc.step();
 *   double[] out = svc.getRawValues();
 */
package {package};

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.apache.commons.math3.ode.FirstOrderIntegrator;
import org.apache.commons.math3.ode.nonstiff.ClassicalRungeKuttaIntegrator;

public class {service_name} implements FruitServiceAPI {{

    public static final String[] OUTPUT_HEADER = {{ {header_entries} }};

    protected final {class_name} model;
    private final FirstOrderIntegrator integrator;
    private final double[] y0;
    private final double[] y1;
    private final double[] output;
    private List<String> outputHeader;
    private int delta;
    private double tDays;

    public {service_name}({class_name} model, int delta) {{
        this.model = model;
        this.delta = delta;
        this.integrator = new ClassicalRungeKuttaIntegrator(delta / 1440.0);
        this.y0 = new double[{class_name}.STATE_COUNT];
        this.y1 = new double[{class_name}.STATE_COUNT];
        this.output = new double[{class_name}.STATE_COUNT];
        this.tDays = 0.0;
        initOutputHeaders();
    }}

    // === Model interface ===

    @Override
    public void init() {{
        model.computeComputedConstants();
        System.arraycopy(model.getStates(), 0, y0, 0, {class_name}.STATE_COUNT);
    }}

    @Override
    public int getOLength() {{ return {class_name}.STATE_COUNT; }}

    @Override
    public double[] getOutput() {{
        System.arraycopy(model.getStates(), 0, output, 0, {class_name}.STATE_COUNT);
        return output;
    }}

    @Override
    public void compute() {{
        System.arraycopy(model.getStates(), 0, y0, 0, {class_name}.STATE_COUNT);
        double stepDays = delta / 1440.0;
        integrator.integrate(model, tDays - stepDays, y0, tDays, y1);
        model.setStates(y1);
    }}

    @Override
    public void link(ArrayList<Model> fms) {{ }}

    // === FruitServiceAPI ===

    @Override
    public void step() {{ compute(); link(new ArrayList<>()); }}

    @Override
    public double[] getRawValues() {{ return getOutput(); }}

    @Override
    public Map<String, Double> getJsonValues() {{
        double[] raw = getRawValues();
        Map<String, Double> node = new LinkedHashMap<>(outputHeader.size());
        for (int j = 0; j < outputHeader.size() && j < raw.length; j++)
            node.put(outputHeader.get(j), raw[j]);
        return Collections.unmodifiableMap(node);
    }}

    @Override
    public void fromArray(int ageMin, double[] values) {{
        if (values != null && values.length > 0)
            model.setParameter("pasfls", values[0]);
        tDays = ageMin / 1440.0;
    }}

    @Override
    public void syncOutputs(Map<String, Double> outputs) {{
        if (outputs == null) return;
        for (Map.Entry<String, Double> e : outputs.entrySet())
            model.setState(e.getKey(), e.getValue());
    }}

    @Override
    public void setDelta(int delta) {{ this.delta = delta; }}

    @Override
    public int getDelta() {{ return delta; }}

    @Override
    public void initOutputHeaders() {{
        outputHeader = new ArrayList<>(Arrays.asList(OUTPUT_HEADER));
    }}

    public {class_name} getModel() {{ return model; }}
}}
"""
    pkg_path = os.path.join(output_dir, package_to_path(package))
    os.makedirs(pkg_path, exist_ok=True)
    filepath = os.path.join(pkg_path, f"{service_name}.java")
    with open(filepath, "w") as f:
        f.write(code)
    return filepath
