/*
 * ServiceExample.java — Simulate WITH the Model/FruitService interface.
 *
 * Uses the package-local Model + FruitServiceAPI interfaces (generated by --with-fruit-service).
 * No jfruit2 dependency — the interfaces are in the same package as the model.
 *
 * This path provides step-driven simulation (compute/step/getOutput/getRawValues)
 * and is structurally compatible with jfruit2's Launch driver and FruitCropXL's
 * FruitService pattern.
 *
 * Compile: javac -cp <commons-math3.jar> gen/org/fruitcropxl/cellml/*.java examples/*.java
 * Run:     java -cp .:<commons-math3.jar> org.fruitcropxl.cellml.ServiceExample
 */
package org.fruitcropxl.cellml;

public class ServiceExample {

    static final String[] HEADER = {"tDays", "mSuc", "mSor", "mFru", "mGlu", "mSta", "mSyn"};

    public static void main(String[] args) {
        // 1. Create the user's concrete model (implements applyBoundaryConditions)
        Jfruit2OracleSim model = new Jfruit2OracleSim(0.01); // pasfls = 0.01 g/day

        // 2. Wrap it in the FruitService (provides step-driven simulation)
        //    delta = 60 minutes (FruitService.DELTA)
        Jfruit2OracleFruitService svc = new Jfruit2OracleFruitService(model, 60);
        svc.init();

        // 3. Step-driven simulation
        int nSteps = 100 * 24; // 100 days, hourly
        System.out.println(String.join(",", HEADER));
        for (int s = 0; s < nSteps; s++) {
            int ageMin = (s + 1) * 60; // age in minutes
            // fromArray sets the forcing + time
            svc.fromArray(ageMin, new double[]{0.01}); // pasfls = 0.01
            // step() does one RK4 integration step
            svc.step();
            // Read results via FruitServiceAPI
            double[] out = svc.getRawValues();
            double tDays = ageMin / 1440.0;
            System.out.println(fmt(tDays) + "," + fmt(out[0]) + "," + fmt(out[1]) + ","
                + fmt(out[2]) + "," + fmt(out[3]) + "," + fmt(out[4]) + "," + fmt(out[5]));
        }

        System.err.println("Service simulation complete: " + nSteps + " steps");
        System.err.println("Model interface: " + (svc instanceof Model ? "Model" : "none"));
        System.err.println("FruitServiceAPI: " + (svc instanceof FruitServiceAPI ? "yes" : "no"));
    }

    static String fmt(double v) {
        return String.format("%.12g", v);
    }
}
